# Upload the iptables.sh file generated by Block-KnownBadIPs.ps1 to an ssh server on 192.168.6.71 Port 2222

# get the credentials to use for ssh connections
$SSHCredential = (Get-Credential -Message "Credential for SSH Server:")
Set-SCPItem -Path ".\iptables.sh" -Destination "~" -Port 2222 -ComputerName "192.168.6.71" -Credential $SSHCredential

Get-SCPItem -Path "~/iptables.sh" -Destination "." -NewName "iptables.sh.tmp" -Port 2222 -ComputerName "192.168.6.71" -Credential $SSHCredential -PathType File

if ((Get-FileHash ".\iptables.sh").Hash -eq (Get-FileHash ".\iptables.sh.tmp").Hash) {
    Write-Host "Success! iptables.sh copied to server"
} else {
    Write-Host "Failed to copy iptables.sh to server"
    throw
}